"""Seed data for default templates and system configuration.

This module provides default PromptTemplates and ReportTemplates that are
created on first run. These are marked as `is_system=True` and have no user_id.
"""
from sqlalchemy.orm import Session
from reconly_core.database.models import PromptTemplate, ReportTemplate


# ═══════════════════════════════════════════════════════════════════════════════
# DEFAULT PROMPT TEMPLATES
# ═══════════════════════════════════════════════════════════════════════════════

DEFAULT_PROMPT_TEMPLATES = [
    {
        "name": "Standard Summary (English)",
        "description": "Default English summarization prompt with structured output",
        "language": "en",
        "target_length": 150,
        "system_prompt": """You are a professional content summarizer.
Create concise, informative summaries in English.
Focus on the most important information and key takeaways.
IMPORTANT: If the original title is not in English, translate it to English.""",
        "user_prompt_template": """Summarize the following content from a {source_type}.

Original Title: {title}

Content:
{content}

IMPORTANT: You MUST follow this exact output format with approximately {target_length} words:

**Title:** [Write the English title here - translate from original if not English]

**Main Topic:** [1-2 sentences: What is this about?]

**Key Points:**
- [Point 1]
- [Point 2]
- [Point 3]

**Conclusion:** [1-2 sentences: What is the key insight?]

CRITICAL: Start your response with "**Title:**" followed by the translated English title.""",
    },
    {
        "name": "Quick Brief (English)",
        "description": "Ultra-short English summary for quick scanning",
        "language": "en",
        "target_length": 50,
        "system_prompt": """You are a content summarizer for busy readers.
Create extremely short, concise summaries in English.
Translate title to English if needed.""",
        "user_prompt_template": """Summarize the following content in at most {target_length} words.

Title: {title}

Content:
{content}

**Title:** [English title]
Answer in 2-3 sentences: What is the key takeaway?""",
    },
]


# ═══════════════════════════════════════════════════════════════════════════════
# DEFAULT REPORT TEMPLATES
# ═══════════════════════════════════════════════════════════════════════════════

DEFAULT_REPORT_TEMPLATES = [
    {
        "name": "Daily Digest (Markdown)",
        "description": "Clean Markdown format for daily digest emails or notes",
        "format": "markdown",
        "template_content": """# {{ feed.name }} - Daily Digest

**Generated:** {{ generated_at.strftime('%Y-%m-%d %H:%M') }}
{% if run_info %}
**Sources processed:** {{ run_info.sources_processed }} | **Items:** {{ run_info.items_processed }}
{% endif %}

---

{% for digest in digests %}
## {{ digest.title }}

{% if digest.author %}*By {{ digest.author }}*{% endif %}
{% if digest.published_at %}| *{{ digest.published_at.strftime('%Y-%m-%d') }}*{% endif %}

{{ digest.summary }}

[Read more]({{ digest.url }})

---

{% endfor %}

*Generated by Reconly*
""",
    },
    {
        "name": "Daily Digest (HTML Email)",
        "description": "Styled HTML format for email newsletters",
        "format": "html",
        "template_content": """<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ feed.name }} - Daily Digest</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { border-bottom: 2px solid #4a90d9; padding-bottom: 10px; margin-bottom: 20px; }
    .header h1 { margin: 0; color: #4a90d9; }
    .meta { color: #666; font-size: 0.9em; }
    .digest-item { margin-bottom: 25px; padding-bottom: 20px; border-bottom: 1px solid #eee; }
    .digest-item h2 { margin: 0 0 10px 0; font-size: 1.2em; }
    .digest-item h2 a { color: #333; text-decoration: none; }
    .digest-item h2 a:hover { color: #4a90d9; }
    .digest-meta { color: #888; font-size: 0.85em; margin-bottom: 10px; }
    .summary { color: #444; }
    .read-more { display: inline-block; margin-top: 10px; color: #4a90d9; text-decoration: none; }
    .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; color: #888; font-size: 0.85em; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <h1>{{ feed.name }}</h1>
    <p class="meta">Daily Digest &bull; {{ generated_at.strftime('%B %d, %Y') }}</p>
  </div>

  {% for digest in digests %}
  <div class="digest-item">
    <h2><a href="{{ digest.url }}">{{ digest.title }}</a></h2>
    <p class="digest-meta">
      {% if digest.author %}{{ digest.author }} &bull; {% endif %}
      {% if digest.published_at %}{{ digest.published_at.strftime('%Y-%m-%d') }} &bull; {% endif %}
      {{ digest.source_type }}
    </p>
    <p class="summary">{{ digest.summary }}</p>
    <a href="{{ digest.url }}" class="read-more">Read full article</a>
  </div>
  {% endfor %}

  <div class="footer">
    <p>Generated by Reconly</p>
    {% if run_info %}
    <p>{{ run_info.sources_processed }} sources &bull; {{ run_info.items_processed }} items processed</p>
    {% endif %}
  </div>
</body>
</html>
""",
    },
]


def seed_default_templates(session: Session, force: bool = False) -> dict:
    """
    Seed the database with default PromptTemplates and ReportTemplates.

    Args:
        session: SQLAlchemy database session
        force: If True, recreate templates even if they exist

    Returns:
        Dict with counts of created templates
    """
    result = {
        "prompt_templates_created": 0,
        "report_templates_created": 0,
        "prompt_templates_skipped": 0,
        "report_templates_skipped": 0,
    }

    # Seed PromptTemplates
    for template_data in DEFAULT_PROMPT_TEMPLATES:
        existing = session.query(PromptTemplate).filter(
            PromptTemplate.name == template_data["name"],
            PromptTemplate.origin == 'builtin',
        ).first()

        if existing and not force:
            result["prompt_templates_skipped"] += 1
            continue

        if existing and force:
            session.delete(existing)

        template = PromptTemplate(
            user_id=None,
            origin='builtin',
            **template_data,
        )
        session.add(template)
        result["prompt_templates_created"] += 1

    # Seed ReportTemplates
    for template_data in DEFAULT_REPORT_TEMPLATES:
        existing = session.query(ReportTemplate).filter(
            ReportTemplate.name == template_data["name"],
            ReportTemplate.origin == 'builtin',
        ).first()

        if existing and not force:
            result["report_templates_skipped"] += 1
            continue

        if existing and force:
            session.delete(existing)

        template = ReportTemplate(
            user_id=None,
            origin='builtin',
            **template_data,
        )
        session.add(template)
        result["report_templates_created"] += 1

    session.commit()
    return result


def get_default_prompt_template(session: Session, language: str = "en") -> PromptTemplate | None:
    """Get the default system prompt template for a language."""
    name = f"Standard Summary ({'German' if language == 'de' else 'English'})"
    return session.query(PromptTemplate).filter(
        PromptTemplate.name == name,
        PromptTemplate.origin == 'builtin',
    ).first()


def get_default_report_template(session: Session, format: str = "markdown") -> ReportTemplate | None:
    """Get the default system report template for a format."""
    if format == "html":
        name = "Daily Digest (HTML Email)"
    else:
        name = "Daily Digest (Markdown)"

    return session.query(ReportTemplate).filter(
        ReportTemplate.name == name,
        ReportTemplate.origin == 'builtin',
    ).first()


def get_default_consolidated_template(session: Session, language: str = "en") -> PromptTemplate | None:
    """Get the default system prompt template for consolidated digests.

    Returns the Standard Summary template since the dedicated Consolidated
    Summary template was removed to simplify onboarding.
    """
    return get_default_prompt_template(session, language)
