<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useForm } from 'vee-validate';
import { toTypedSchema } from '@vee-validate/zod';
import * as z from 'zod';
import { useMutation, useQueryClient } from '@tanstack/vue-query';
import { reportTemplatesApi } from '@/services/api';
import type { ReportTemplate } from '@/types/entities';
import { X, Loader2, Code, FileType, Copy } from 'lucide-vue-next';

interface Props {
  isOpen: boolean;
  template?: ReportTemplate | null;
}

interface Emits {
  (e: 'close'): void;
  (e: 'success'): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const queryClient = useQueryClient();

// Validation schema
const formSchema = toTypedSchema(
  z.object({
    name: z.string().min(1, 'Name is required').max(200, 'Name is too long'),
    description: z.string().max(500, 'Description is too long').optional(),
    format: z.enum(['markdown', 'html', 'text'], {
      errorMap: () => ({ message: 'Select a format' }),
    }),
    template_content: z.string().min(10, 'Template content must be at least 10 characters'),
  })
);

const { defineField, handleSubmit, resetForm, errors } = useForm({
  validationSchema: formSchema,
  initialValues: {
    name: '',
    description: '',
    format: 'markdown' as const,
    template_content: '',
  },
});

const [name, nameAttrs] = defineField('name');
const [description, descriptionAttrs] = defineField('description');
const [format, formatAttrs] = defineField('format');
const [template_content, templateContentAttrs] = defineField('template_content');

// Watch for template prop changes (edit mode)
watch(
  () => props.template,
  (newTemplate) => {
    if (newTemplate) {
      resetForm({
        values: {
          name: newTemplate.name,
          description: newTemplate.description || '',
          format: newTemplate.format as 'markdown' | 'html' | 'text',
          template_content: newTemplate.template_content,
        },
      });
    } else {
      resetForm();
    }
  },
  { immediate: true }
);

const isEditMode = computed(() => !!props.template);
const isCopying = ref(false);

// Create/Update mutation
const saveMutation = useMutation({
  mutationFn: async (data: any) => {
    if (isEditMode.value && props.template && !isCopying.value) {
      return await reportTemplatesApi.update(props.template.id, data);
    } else {
      // Create new (either new template or copy)
      return await reportTemplatesApi.create(data);
    }
  },
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['report-templates'] });
    emit('success');
    emit('close');
    resetForm();
    isCopying.value = false;
  },
  onError: (error: any) => {
    console.error('Failed to save report template:', error);
    isCopying.value = false;
  },
});

// Watch for modal open to reset mutation state
watch(
  () => props.isOpen,
  (isOpen) => {
    if (isOpen) {
      saveMutation.reset();
    }
  }
);

// Computed for reactive pending state
const isSaving = computed(() => saveMutation.isPending.value);

const onSubmit = handleSubmit((values) => {
  saveMutation.mutate(values);
});

const handleClose = () => {
  if (!isSaving.value) {
    emit('close');
    resetForm();
    isCopying.value = false;
  }
};

const handleCreateCopy = handleSubmit((values) => {
  isCopying.value = true;
  saveMutation.mutate({
    ...values,
    name: `Copy of ${values.name}`,
  });
});

const formatPlaceholder = computed(() => {
  if (format.value === 'markdown') {
    return `# {{ digest.title }}

**Date:** {{ digest.created_at }}

## Summary
{{ digest.summary }}

## Key Points
{% for point in digest.key_points %}
- {{ point }}
{% endfor %}

---
*Generated by Reconly*`;
  } else if (format.value === 'html') {
    return `<!DOCTYPE html>
<html>
<head>
  <title>{{ digest.title }}</title>
</head>
<body>
  <h1>{{ digest.title }}</h1>
  <p><strong>Date:</strong> {{ digest.created_at }}</p>

  <h2>Summary</h2>
  <p>{{ digest.summary }}</p>

  <h2>Key Points</h2>
  <ul>
  {% for point in digest.key_points %}
    <li>{{ point }}</li>
  {% endfor %}
  </ul>
</body>
</html>`;
  } else {
    return `{{ digest.title }}
Date: {{ digest.created_at }}

Summary:
{{ digest.summary }}

Key Points:
{% for point in digest.key_points %}
- {{ point }}
{% endfor %}`;
  }
});
</script>

<template>
  <Teleport to="body">
    <Transition name="modal">
      <div
        v-if="isOpen"
        class="fixed inset-0 z-50 flex items-center justify-center p-4"
        @mousedown.self="handleClose"
      >
        <!-- Backdrop -->
        <div class="absolute inset-0 bg-black/80 backdrop-blur-sm" />

        <!-- Modal -->
        <div
          class="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl border border-border-default bg-gradient-to-br from-bg-elevated to-bg-surface shadow-2xl shadow-black/50"
        >
          <!-- Decorative gradient orb -->
          <div class="pointer-events-none absolute -right-20 -top-20 h-40 w-40 rounded-full bg-orange-500/20 blur-3xl" />

          <!-- Sticky Header -->
          <div class="sticky top-0 z-10 border-b border-border-subtle bg-bg-elevated/95 backdrop-blur-sm p-6">
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-3">
                <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-orange-500/10">
                  <Code :size="20" class="text-orange-400" :stroke-width="2" />
                </div>
                <h2 class="text-2xl font-bold text-text-primary">
                  {{ isEditMode ? 'Edit Report Template' : 'Create Report Template' }}
                </h2>
              </div>
              <button
                @click="handleClose"
                :disabled="isSaving"
                class="rounded-lg p-2 text-text-muted transition-colors hover:bg-bg-hover hover:text-text-primary disabled:opacity-50"
              >
                <X :size="20" />
              </button>
            </div>
          </div>

          <!-- Form -->
          <form @submit.prevent="onSubmit" class="p-6 space-y-6">
            <!-- Name -->
            <div>
              <label for="name" class="mb-2 block text-sm font-medium text-text-primary">
                Template Name
              </label>
              <input
                id="name"
                v-model="name"
                v-bind="nameAttrs"
                type="text"
                placeholder="Clean Markdown Report"
                class="w-full rounded-lg border bg-bg-surface px-4 py-3 text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-bg-base transition-all"
                :class="
                  errors.name
                    ? 'border-status-failed focus:ring-status-failed'
                    : 'border-border-subtle focus:border-accent-primary focus:ring-accent-primary'
                "
              />
              <Transition name="error">
                <p v-if="errors.name" class="mt-2 text-sm text-status-failed">{{ errors.name }}</p>
              </Transition>
            </div>

            <!-- Description -->
            <div>
              <label for="description" class="mb-2 block text-sm font-medium text-text-primary">
                Description <span class="text-text-muted">(optional)</span>
              </label>
              <textarea
                id="description"
                v-model="description"
                v-bind="descriptionAttrs"
                rows="2"
                placeholder="Clean markdown format suitable for email and documentation"
                class="w-full rounded-lg border bg-bg-surface px-4 py-3 text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-bg-base transition-all resize-none"
                :class="
                  errors.description
                    ? 'border-status-failed focus:ring-status-failed'
                    : 'border-border-subtle focus:border-accent-primary focus:ring-accent-primary'
                "
              />
              <Transition name="error">
                <p v-if="errors.description" class="mt-2 text-sm text-status-failed">{{ errors.description }}</p>
              </Transition>
            </div>

            <!-- Format -->
            <div>
              <label for="format" class="mb-2 block text-sm font-medium text-text-primary">
                Output Format
              </label>
              <div class="relative">
                <FileType class="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted" :size="18" />
                <select
                  id="format"
                  v-model="format"
                  v-bind="formatAttrs"
                  class="w-full rounded-lg border bg-bg-surface pl-10 pr-4 py-3 text-text-primary focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-bg-base transition-all"
                  :class="
                    errors.format
                      ? 'border-status-failed focus:ring-status-failed'
                      : 'border-border-subtle focus:border-accent-primary focus:ring-accent-primary'
                  "
                >
                  <option value="markdown">Markdown (.md)</option>
                  <option value="html">HTML (.html)</option>
                  <option value="text">Plain Text (.txt)</option>
                </select>
              </div>
              <Transition name="error">
                <p v-if="errors.format" class="mt-2 text-sm text-status-failed">{{ errors.format }}</p>
              </Transition>
            </div>

            <!-- Template Content -->
            <div>
              <label for="template_content" class="mb-2 block text-sm font-medium text-text-primary">
                Jinja2 Template Content
              </label>
              <textarea
                id="template_content"
                v-model="template_content"
                v-bind="templateContentAttrs"
                :placeholder="formatPlaceholder"
                rows="16"
                class="w-full rounded-lg border bg-bg-surface px-4 py-3 font-mono text-sm text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-bg-base transition-all resize-none"
                :class="
                  errors.template_content
                    ? 'border-status-failed focus:ring-status-failed'
                    : 'border-border-subtle focus:border-accent-primary focus:ring-accent-primary'
                "
              />
              <p class="mt-2 text-xs text-text-muted">
                Use Jinja2 syntax with variables like
                <code class="rounded bg-bg-hover px-1 py-0.5 font-mono text-orange-400">&#123;&#123; digest.title &#125;&#125;</code>,
                <code class="rounded bg-bg-hover px-1 py-0.5 font-mono text-orange-400">&#123;&#123; digest.summary &#125;&#125;</code>, and
                <code class="rounded bg-bg-hover px-1 py-0.5 font-mono text-orange-400">&#123;% for %&#125;</code> loops
              </p>
              <Transition name="error">
                <p v-if="errors.template_content" class="mt-2 text-sm text-status-failed">{{ errors.template_content }}</p>
              </Transition>
            </div>

            <!-- Actions -->
            <div class="flex gap-3 pt-4">
              <button
                type="button"
                @click="handleClose"
                :disabled="isSaving"
                class="flex-1 rounded-lg border border-border-subtle bg-bg-surface px-6 py-3 font-medium text-text-primary transition-all hover:bg-bg-hover disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                :disabled="isSaving"
                class="flex-1 rounded-lg bg-accent-primary px-6 py-3 font-medium text-white transition-all hover:bg-accent-primary-hover disabled:opacity-50 flex items-center justify-center gap-2"
              >
                <Loader2
                  v-if="isSaving"
                  :size="18"
                  class="animate-spin"
                />
                {{ isSaving ? 'Saving...' : (isEditMode ? 'Update Template' : 'Create Template') }}
              </button>
            </div>

            <!-- Create Copy Link (only in edit mode) -->
            <div v-if="isEditMode" class="pt-3 text-center">
              <button
                type="button"
                @click="handleCreateCopy"
                :disabled="isSaving"
                class="inline-flex items-center gap-1.5 text-sm text-text-muted transition-all hover:text-accent-primary hover:underline underline-offset-2 disabled:opacity-50"
              >
                <Copy :size="14" />
                Create a Copy
              </button>
            </div>
          </form>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
/* Modal transitions */
.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}

.modal-enter-active > div:last-child,
.modal-leave-active > div:last-child {
  transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}

.modal-enter-from > div:last-child,
.modal-leave-to > div:last-child {
  transform: scale(0.95) translateY(20px);
  opacity: 0;
}

/* Error message transitions */
.error-enter-active,
.error-leave-active {
  transition: all 0.2s ease;
}

.error-enter-from,
.error-leave-to {
  opacity: 0;
  transform: translateY(-4px);
}

/* Custom scrollbar */
.overflow-y-auto::-webkit-scrollbar {
  width: 8px;
}

.overflow-y-auto::-webkit-scrollbar-track {
  background: var(--color-bg-surface);
  border-radius: 4px;
}

.overflow-y-auto::-webkit-scrollbar-thumb {
  background: var(--color-bg-hover);
  border-radius: 4px;
}

.overflow-y-auto::-webkit-scrollbar-thumb:hover {
  background: var(--color-border-default);
}
</style>
